#!/bin/sh
#***********************************************************************#
#	a script to open vterm or running a command for each 	     	#
#	         machine in a bash tab of konsole		     	#
#***********************************************************************#	

# NOTE: *.base on konsole & a expect script: vterm.exp (for open vterm. for run a 
#	  command see below.)
#	*.konsole must has a session named "vterm", which run vterm.exp
#	*.for run a command in a bash tab for each machine, konsole must has a 
#	  session named "bash"; and the title of the session is empty

usage()
{
	cat <<-EOF
	Usage:
	1. $0 -r command host1 host2 ...: run command for each machine in a konsole tab;
	2. $0 host1 host2 ....: open vterm of each machine in a konsole tab;
	use -h for help.
	EOF
	exit 0
}

cmd=
session=vterm

while getopts "r:h" opt
do
	case $opt in
		r) cmd=$OPTARG;session=bash;shift 2;;
		*) usage;;
	esac
done

[[ $# -lt 1 ]] && usage

tab_open()
{
	session_id=$(qdbus org.kde.konsole /Konsole org.kde.konsole.Konsole.newSession)
	sleep 1
	case $session in
		vterm)
		qdbus org.kde.konsole /Sessions/${session_id} org.kde.konsole.Session.sendText "$1"
		;;
		bash)
		qdbus org.kde.konsole /Sessions/${session_id} org.kde.konsole.Session.sendText "$cmd $1"
		;;
		*)
		# are you sure???
		;;
	esac
	qdbus org.kde.konsole /Sessions/${session_id} org.kde.konsole.Session.setTitle 0 "$1"
}

for h in $*
do
	tab_open $h &
done
